version: "3"

services:
  nginx:
    hostname: nginx
    image: registry.cn-chengdu.aliyuncs.com/shy-base/nginx:1.22
    container_name: nginx
    privileged: true
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8010:8010
      - 8021:8021
      - 8022:8022
      - 8031:8031
      - 8032:8032
      - 8040:8040
      - 8041:8041
      - 8050:8050
      - 8051:8051
      - 8052:8052
      - 8070:8070
      - 8071:8071
      - 8072:8072
    volumes:
      - /root/repo/study/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/repo/study/nginx/conf.d:/etc/nginx/conf.d
      - /root/repo/study/nginx/html:/usr/share/nginx/html
      - /root/repo/study/nginx/ssl:/opt/ssl
